import type { CaseWithAssignee, TimelineEventWithAuthor, PipelineStage } from "@/types";

export const mockUsers = [
  {
    id: "user-1",
    name: "Robert Hayes",
    email: "robert@hayeslawfirm.com",
    role: "admin" as const,
    avatarUrl: null,
    lawFirmId: "firm-1",
    passwordHash: null,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "user-2",
    name: "Maria Torres",
    email: "maria@hayeslawfirm.com",
    role: "member" as const,
    avatarUrl: null,
    lawFirmId: "firm-1",
    passwordHash: null,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

export const mockCases: CaseWithAssignee[] = [
  // New Lead
  {
    id: "case-1",
    lawFirmId: "firm-1",
    assignedToId: "user-2",
    clientName: "James Whitfield",
    clientEmail: "j.whitfield@email.com",
    clientPhone: "+13055550101",
    clientPhone2: null,
    caseTitle: "Auto Accident - I-95",
    caseType: "Personal Injury",
    pipelineStage: "new_lead",
    sortOrder: 0,
    notes: "Rear-ended on I-95 northbound. Client has medical bills.",
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-06-20"),
    updatedAt: new Date("2025-06-20"),
    assignedTo: { id: "user-2", name: "Maria Torres", avatarUrl: null },
  },
  {
    id: "case-2",
    lawFirmId: "firm-1",
    assignedToId: null,
    clientName: "Sandra Okoye",
    clientEmail: "sandra.okoye@gmail.com",
    clientPhone: "+17865550234",
    clientPhone2: null,
    caseTitle: "Slip and Fall - Publix",
    caseType: "Personal Injury",
    pipelineStage: "new_lead",
    sortOrder: 1,
    notes: null,
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-06-22"),
    updatedAt: new Date("2025-06-22"),
    assignedTo: null,
  },
  {
    id: "case-3",
    lawFirmId: "firm-1",
    assignedToId: "user-1",
    clientName: "Carlos Mendez",
    clientEmail: null,
    clientPhone: "+13055550312",
    clientPhone2: null,
    caseTitle: "Work Injury - Construction Site",
    caseType: "Workers Compensation",
    pipelineStage: "new_lead",
    sortOrder: 2,
    notes: "Fell from scaffolding. No current representation.",
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-06-24"),
    updatedAt: new Date("2025-06-24"),
    assignedTo: { id: "user-1", name: "Robert Hayes", avatarUrl: null },
  },

  // Case Evaluation
  {
    id: "case-4",
    lawFirmId: "firm-1",
    assignedToId: "user-1",
    clientName: "Patricia Dunn",
    clientEmail: "pdunn@outlook.com",
    clientPhone: "+19545550445",
    clientPhone2: null,
    caseTitle: "Medical Malpractice - Misdiagnosis",
    caseType: "Medical Malpractice",
    pipelineStage: "case_evaluation",
    sortOrder: 0,
    notes: "Delayed cancer diagnosis. Gathering medical records.",
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-06-10"),
    updatedAt: new Date("2025-06-18"),
    assignedTo: { id: "user-1", name: "Robert Hayes", avatarUrl: null },
  },
  {
    id: "case-5",
    lawFirmId: "firm-1",
    assignedToId: "user-2",
    clientName: "Anthony Rivera",
    clientEmail: "anthony.r@yahoo.com",
    clientPhone: "+13055550567",
    clientPhone2: "+13055550568",
    caseTitle: "DUI Arrest - Brickell Ave",
    caseType: "Criminal Defense",
    pipelineStage: "case_evaluation",
    sortOrder: 1,
    notes: null,
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-06-15"),
    updatedAt: new Date("2025-06-21"),
    assignedTo: { id: "user-2", name: "Maria Torres", avatarUrl: null },
  },

  // Retainer Sent
  {
    id: "case-6",
    lawFirmId: "firm-1",
    assignedToId: "user-1",
    clientName: "Emily Chen",
    clientEmail: "emily.chen@gmail.com",
    clientPhone: "+17865550678",
    clientPhone2: null,
    caseTitle: "Wrongful Termination",
    caseType: "Employment Law",
    pipelineStage: "retainer_sent",
    sortOrder: 0,
    notes: "Retainer sent 6/18. Waiting on signature and payment.",
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-06-01"),
    updatedAt: new Date("2025-06-18"),
    assignedTo: { id: "user-1", name: "Robert Hayes", avatarUrl: null },
  },
  {
    id: "case-7",
    lawFirmId: "firm-1",
    assignedToId: "user-2",
    clientName: "Michael Johanssen",
    clientEmail: "m.johanssen@hotmail.com",
    clientPhone: "+13055550789",
    clientPhone2: null,
    caseTitle: "Rear-End Collision - Aventura",
    caseType: "Personal Injury",
    pipelineStage: "retainer_sent",
    sortOrder: 1,
    notes: null,
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-06-05"),
    updatedAt: new Date("2025-06-17"),
    assignedTo: { id: "user-2", name: "Maria Torres", avatarUrl: null },
  },

  // Case Management
  {
    id: "case-8",
    lawFirmId: "firm-1",
    assignedToId: "user-1",
    clientName: "Denise Kaminski",
    clientEmail: "denise.k@gmail.com",
    clientPhone: "+19545550890",
    clientPhone2: null,
    caseTitle: "Dog Bite Incident",
    caseType: "Personal Injury",
    pipelineStage: "case_management",
    sortOrder: 0,
    notes: "Liability established. Negotiating with insurance.",
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-04-12"),
    updatedAt: new Date("2025-06-20"),
    assignedTo: { id: "user-1", name: "Robert Hayes", avatarUrl: null },
  },
  {
    id: "case-9",
    lawFirmId: "firm-1",
    assignedToId: "user-1",
    clientName: "Rafael Suarez",
    clientEmail: "rafael.suarez@icloud.com",
    clientPhone: "+13055550912",
    clientPhone2: null,
    caseTitle: "Premises Liability - Mall",
    caseType: "Personal Injury",
    pipelineStage: "case_management",
    sortOrder: 1,
    notes: null,
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-03-20"),
    updatedAt: new Date("2025-06-15"),
    assignedTo: { id: "user-1", name: "Robert Hayes", avatarUrl: null },
  },
  {
    id: "case-10",
    lawFirmId: "firm-1",
    assignedToId: "user-2",
    clientName: "Janet Moreira",
    clientEmail: "janetm@gmail.com",
    clientPhone: "+17865551023",
    clientPhone2: null,
    caseTitle: "SSDI Application",
    caseType: "Social Security",
    pipelineStage: "case_management",
    sortOrder: 2,
    notes: "Initial application denied, working on appeal.",
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-02-14"),
    updatedAt: new Date("2025-06-10"),
    assignedTo: { id: "user-2", name: "Maria Torres", avatarUrl: null },
  },

  // Litigation
  {
    id: "case-11",
    lawFirmId: "firm-1",
    assignedToId: "user-1",
    clientName: "Thomas Brennan",
    clientEmail: "t.brennan@email.com",
    clientPhone: "+13055551134",
    clientPhone2: null,
    caseTitle: "Multi-Vehicle Crash - SR-836",
    caseType: "Personal Injury",
    pipelineStage: "litigation",
    sortOrder: 0,
    notes: "Filed suit 3/1. Discovery phase ongoing.",
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2025-06-22"),
    assignedTo: { id: "user-1", name: "Robert Hayes", avatarUrl: null },
  },
  {
    id: "case-12",
    lawFirmId: "firm-1",
    assignedToId: "user-1",
    clientName: "Luisa Vega",
    clientEmail: "luisa.v@gmail.com",
    clientPhone: "+19545551245",
    clientPhone2: null,
    caseTitle: "Trip and Fall - City Sidewalk",
    caseType: "Personal Injury",
    pipelineStage: "litigation",
    sortOrder: 1,
    notes: "Trial set for September 2025.",
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2024-09-05"),
    updatedAt: new Date("2025-06-18"),
    assignedTo: { id: "user-1", name: "Robert Hayes", avatarUrl: null },
  },

  // Dropped
  {
    id: "case-13",
    lawFirmId: "firm-1",
    assignedToId: null,
    clientName: "George Patel",
    clientEmail: null,
    clientPhone: "+13055551356",
    clientPhone2: null,
    caseTitle: "Fender Bender - Minor Damages",
    caseType: "Personal Injury",
    pipelineStage: "dropped",
    sortOrder: 0,
    notes: "Client accepted low insurance offer without consulting us.",
    notionPageId: null,
    quoContactId: null,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-05-15"),
    assignedTo: null,
  },
];

export const mockTimelineEvents: Record<string, TimelineEventWithAuthor[]> = {
  "case-8": [
    {
      id: "evt-1",
      caseId: "case-8",
      authorId: "user-1",
      type: "note",
      content: "Spoke with State Farm adjuster. Initial offer is $12,500 — way below medical specials. Countered at $85,000.",
      metadata: null,
      occurredAt: new Date("2025-06-20T14:30:00Z"),
      externalId: null,
      createdAt: new Date("2025-06-20T14:30:00Z"),
      author: { id: "user-1", name: "Robert Hayes", avatarUrl: null },
    },
    {
      id: "evt-2",
      caseId: "case-8",
      authorId: null,
      type: "call",
      content: "Inbound call from client. Discussing settlement options and medical treatment status.",
      metadata: {
        direction: "inbound",
        duration_seconds: 847,
        quo_call_id: "quo-call-001",
      },
      occurredAt: new Date("2025-06-18T10:15:00Z"),
      externalId: "quo-call-001",
      createdAt: new Date("2025-06-18T10:15:00Z"),
      author: null,
    },
    {
      id: "evt-3",
      caseId: "case-8",
      authorId: null,
      type: "call_summary",
      content: "Client confirmed she is still receiving physical therapy (2x/week at Miami PT Center). Pain levels have improved from 8/10 to 5/10. She is concerned about future medical costs. Attorney discussed the importance of completing treatment before settlement. No final decision on counter-offer yet.",
      metadata: { quo_call_id: "quo-call-001" },
      occurredAt: new Date("2025-06-18T10:15:00Z"),
      externalId: "quo-summary-001",
      createdAt: new Date("2025-06-18T10:20:00Z"),
      author: null,
    },
    {
      id: "evt-4",
      caseId: "case-8",
      authorId: null,
      type: "sms",
      content: "Hi Denise, just following up on the documents we need. Can you send the PT records from last month?",
      metadata: { direction: "outbound", quo_message_id: "quo-sms-001" },
      occurredAt: new Date("2025-06-17T09:00:00Z"),
      externalId: "quo-sms-001",
      createdAt: new Date("2025-06-17T09:00:00Z"),
      author: null,
    },
    {
      id: "evt-5",
      caseId: "case-8",
      authorId: null,
      type: "sms",
      content: "Of course! I'll send them over this afternoon. Thank you for everything.",
      metadata: { direction: "inbound", quo_message_id: "quo-sms-002" },
      occurredAt: new Date("2025-06-17T11:32:00Z"),
      externalId: "quo-sms-002",
      createdAt: new Date("2025-06-17T11:32:00Z"),
      author: null,
    },
    {
      id: "evt-6",
      caseId: "case-8",
      authorId: "user-1",
      type: "status_change",
      content: "Case moved to Case Management",
      metadata: { from_stage: "retainer_sent", to_stage: "case_management" },
      occurredAt: new Date("2025-04-14T16:00:00Z"),
      externalId: null,
      createdAt: new Date("2025-04-14T16:00:00Z"),
      author: { id: "user-1", name: "Robert Hayes", avatarUrl: null },
    },
  ],
};
